---
# Debian/Ubuntu specific tasks

- name: Webupd8 apt key
  apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: EEA14886
      state: present

- name: Enable Webupd8 repos
  apt_repository:
      repo: deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main
      state: present

- name: Accept Oracle EULA
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: Install required debian packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
      - oracle-java8-installer
      - tomcat7
      - libapache2-mod-jk
      - oracle-java8-unlimited-jce-policy

- name: Set Tomcat java home
  lineinfile: dest=/etc/default/tomcat7 regexp="^JAVA_HOME=" line="JAVA_HOME=/usr/lib/jvm/java-8-oracle/" state=present

