---
# Tasks to install nginx httpd and php

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific taks
  include: "{{ ansible_os_family }}.yml"

- name: nginx service state
  service: name="{{ nginx_service_name }}" state=started enabled=yes
  when: not skip_httpd_restart

- name: setup fs
  file: path={{ item.path }} owner='root' group='root' mode=755 state=directory
  with_items:
      - path: /srv
      - path: /srv/www
      - path: /srv/www/vhosts

- name: set SELinux fcontext
  shell: semanage fcontext -t {{ item.type }} -a "{{ item.target }}(/.*)?"
  with_items:
      - target: '/srv/www'
        type: httpd_sys_rw_content_t
  when: selinux_host is defined and selinux_host

- name: set SELinux fcontext part2
  shell: restorecon -R "{{ item.target }}"
  with_items:
      - target: '/srv/www'
  when: selinux_host is defined and selinux_host

- stat: path="{{ nginx_conf_file }}"
  register: nginx_conf_file_exists

- name: Make sure nginx conf file exists
  copy: dest="{{ nginx_conf_file }}" content=""
  when: nginx_conf_file_exists.stat.exists == False

- name: set SELinux httpd_can_sendmail
  shell: setsebool -P httpd_can_sendmail on
  when: selinux_host is defined and selinux_host

- name: Tighten down nginx security
  lineinfile: dest="{{ nginx_conf_file }}" regexp="{{ item.regexp }}" line="{{ item.line }}" state=present
  with_items: 
    - regexp: "^server_tokens*"
      line: "server_tokens off;"
  notify: restart nginx

- name: sync noindex
  synchronize: src=files/noindex dest={{ item.documentroot }}
  when: item.welcome is defined and item.welcome
  with_items: '{{ nginx_vhosts }}'

- name: set noindex perms
  file: recurse=yes path={{ item.documentroot }}  owner='{{nginx_user}}' group='{{nginx_group}}' mode=755
  when: item.welcome is defined and item.welcome
  with_items: '{{ nginx_vhosts }}'

- name: sync noindex default docroot
  synchronize: src=files/noindex/ dest={{ default_docroot }}/
  with_items: '{{ nginx_vhosts }}'
  when: default_docroot is defined

- name: set default docroot perms
  file: recurse=yes path={{ default_docroot }}/ owner='{{nginx_user}}' group='{{nginx_group}}' mode=755
  when: item.welcome is defined and item.welcome
  with_items: '{{ nginx_vhosts }}'

- name: remove defaultconf
  file: path={{ item.path }} state=absent
  with_items: '{{ nginx_remove_files }}'

- name: setup lets encrypt SSL
  shell: certbot certonly --keep -n --nginx -m "{{ item.admin_from_email }}" -d "{{ item.servername }}" --agree-tos
  when: item.use_https is defined and item.use_https
  with_items: "{{ nginx_vhosts }}"
  notify: restart nginx

- name: setup vhosts
  template:
      src: "vhosts.conf.j2"
      dest: "{{ nginx_sites_conf_dir }}/{{ item.servername }}.conf"
      owner: root
      group: root
      mode: 0644
  with_items: "{{ nginx_vhosts }}"
  notify: restart nginx

- name: enable vhost config
  file: 
      dest: "{{ nginx_sites_conf_enabled_dir }}/{{ item.servername }}.conf"
      src: "{{ nginx_sites_conf_dir }}/{{ item.servername }}.conf"
      state: link
  with_items: "{{ nginx_vhosts }}"
  when: nginx_sites_conf_enabled_dir!=nginx_sites_conf_dir
  notify: restart nginx

- name: Include PHP tasks
  include: "php.yml"
