---
# Tasks to install postfix mailforwarder

- name: Include OS-specific tasks
  include: "{{ ansible_os_family }}.yml"

- name: service state
  service: name={{ item }} state=started enabled=yes
  with_items:
      - postfix

- name: set postfix options
  lineinfile: dest="{{ postfix_conf_dir }}/main.cf" regexp={{ item.regexp }} line={{ item.line }} state=present
  with_items:
    - regexp: "^#?relayhost" 
      line: "relayhost = {{ postfix_relay_host }}"

- name: absent virtual alias domains
  lineinfile:  dest="{{ postfix_conf_dir }}/main.cf" regexp="{{ item.regexp }}" state=absent
  with_items:
      - regexp: "^virtual_alias_domains"
      - regexp: "^virtual_alias_maps"
  notify: restart postfix

- name: iptables public input absent
  iptables: 
      chain: "{{ iptables_input_chain }}"
      destination: 0.0.0.0/0
      ctstate: NEW
      protocol: tcp
      destination_port: "{{ item }}"
      source: 0.0.0.0/0
      jump: ACCEPT
      state: absent
  with_items:
      - 25
      - 465

- name: iptables local input allow
  iptables: 
      chain: "{{ iptables_input_chain }}"
      destination: 127.0.0.1/8
      ctstate: NEW
      protocol: tcp
      in_interface: lo
      destination_port: "{{ item }}"
      source: 127.0.0.1/8
      jump: ACCEPT
      state: present
  with_items:
      - 25
      - 465

- name: iptables public input drop
  iptables: 
      chain: "{{ iptables_input_chain }}"
      destination: 0.0.0.0/0
      ctstate: NEW
      protocol: tcp
      in_interface: "{{ public_eth }}"
      destination_port: "{{ item }}"
      source: 0.0.0.0/0
      jump: DROP
      state: present
  with_items:
      - 25
      - 465

