---
# Tasks to install python gunicorn and circus
#
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific taks
  include: "{{ ansible_os_family }}.yml"

- name: Intall python3 packages
  pip: executable=pip3 name={{ item }} state=present
  with_items:
      - virtualenv
      - virtualenvwrapper
      - psycopg2
      - configobj
      - mysqlclient
      - py-bcrypt

- name: Intall python packages
  pip: executable=pip name={{ item }} state=present
  with_items:
      - virtualenv
      - virtualenvwrapper
      - psycopg2
      - configobj
      - mysqlclient
      - py-bcrypt

- name: Install circus python packages
  pip: executable=pip3 name={{ item }} state=present
  with_items:
      - circus
  when: python_run_circus

- name: Install gunicorn python packages
  pip: executable=pip3 name={{ item }} state=present
  with_items:
      - gunicorn
  when: python_run_gunicorn

- name: Install supervisor python packages
  pip: executable=pip name={{ item }} state=present
  with_items:
      - supervisor
  when: python_run_supervisor
